dist: trusty
sudo: required
language: cpp
compiler: gcc
cache: ccache


addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
before_script:
  - export CXX="g++-5" CC="gcc-5"
  - sudo apt-get -qq update
  - sudo apt-get install libhdf5-serial-dev cmake git-core libboost-all-dev build-essential libfftw3-dev h5utils hdf5-tools python-dev python-numpy liblapack-dev libxml2-dev libxslt-dev libarmadillo-dev libace-dev python-h5py python-matplotlib python-libxml2 gcc-multilib python-psutil libgtest-dev libplplot-dev
  - git clone --depth=1 https://github.com/ismrmrd/ismrmrd.git
  - pushd ismrmrd && mkdir build && pushd build && cmake .. && make && sudo make install && popd && popd

  - git clone --depth=1  https://github.com/ismrmrd/siemens_to_ismrmrd.git
  - pushd siemens_to_ismrmrd && mkdir build && pushd build && cmake .. && make && sudo make install  && popd && popd
  - git clone --depth=1 https://github.com/conradsnicta/armadillo-code.git -b 8.200.x
  - pushd armadillo-code && cmake . && make && sudo make install && popd

  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 2