# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  containers:
    - container: ubuntu
      image: gadgetron/ubuntu_1604_base  

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  container: ubuntu
  steps:
  - script: |
      mkdir ~/opt/code
      cd ~/opt/code
      git clone https://github.com/ismrmrd/ismrmrd.git
      cd ismrmrd
      mkdir build
      cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=~/opt
      make -j
      make install
  - script: |
      cd ~/opt/code
      git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
      cd siemens_to_ismrmrd
      mkdir build
      cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=~/opt
      make -j
      make install
  - script: |
      mkdir build
      cd build 
      cmake .. -DCMAKE_PREFIX_PATH=~/opt:/usr/local:/usr 
      cmake --build . --config Release
      cmake --install . --config Release