# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  containers:
    - container: ubuntu
      image: gadgetron/ubuntu_1604_base  

jobs:
- job: Linux
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-16.04'
  container: ubuntu
  steps:
  - script: |
      mkdir ~/opt/code
      cd ~/opt/code
      git clone https://github.com/ismrmrd/ismrmrd.git
      cd ismrmrd
      mkdir build
      cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=~/opt
      make -j
      make install
  - script: |
      cd ~/opt/code
      git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
      cd siemens_to_ismrmrd
      mkdir build
      cd build
      cmake .. -DCMAKE_INSTALL_PREFIX=~/opt
      make -j
      make install
  - script: |
      export ISMRMRD_HOME=~/opt
      mkdir build
      cd build 
      cmake .. -DCMAKE_PREFIX_PATH=~/opt:/usr/local:/usr -DBUILD_WITH_PYTHON3=ON -DCMAKE_INSTALL_PREFIX=~/opt
      make -j2
      make install
      export GADGETRON_HOME=~/opt
      cp ~/opt/share/gadgetron/config/gadgetron.xml.example ~/opt/share/gadgetron/config/gadgetron.xml
  - script: |
      cd test/integration
      python get_data.py
      python3 run_tests.py cases/*
