# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    cd /opt/code
    git clone https://github.com/ismrmrd/ismrmrd.git
    cd ismrmrd
    mkdir build
    cd build
    cmake ..
    make -j
    make install
  displayName: 'Build ISMRMRD'

- script: pip3 install ismrmrd
  displayName: 'Install Python ISMRMRD'

- script: |
    cd /opt/code
    git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
    cd siemens_to_ismrmrd
    mkdir build
    cd build
    cmake ../
    make -j
    make install 
  displayName: "Build Siemens to ISMRMRD"

- script: |
    mkdir build
    cmake ..
    make -j
    make install
  displayName: 'Build Gadgetron'
