# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo apt-get update --quiet
    sudo apt-get install --no-install-recommends --no-install-suggests --yes software-properties-common apt-utils wget build-essential cython3  python3-dev python3-pip libhdf5-serial-dev cmake git-core libboost-all-dev libfftw3-dev h5utils jq hdf5-tools liblapack-dev libatlas-base-dev libxml2-dev libfreetype6-dev pkg-config libxslt-dev libarmadillo-dev libace-dev gcc-multilib libgtest-dev python3-dev liblapack-dev liblapacke-dev libplplot-dev libdcmtk-dev supervisor cmake-curses-gui neofetch supervisor net-tools cpio libpugixml-dev jove libpugixml-dev
    sudo apt-get install --no-install-recommends --no-install-suggests --yes libopenblas-base libopenblas-dev 

    sudo apt-get install -y python3-h5py
    pip3 install -U pip setuptools

    pip3 install numpy==1.15.4 scipy Cython tk-tools matplotlib==2.2.3 scikit-image opencv_python pydicom scikit-learn
    sudo apt-get install --no-install-recommends --no-install-suggests --yes python3-psutil python3-pyxb python3-lxml
    sudo apt-get install --no-install-recommends --no-install-suggests --yes python3-pil
    DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends --no-install-suggests --yes python3-tk

- script: |
    cd /opt/code
    git clone https://github.com/ismrmrd/ismrmrd.git
    cd ismrmrd
    mkdir build
    cd build
    cmake ..
    make -j
    sudo make install
  displayName: 'Build ISMRMRD'

- script: python3 -m pip install ismrmrd
  displayName: 'Install Python ISMRMRD'

- script: |
    cd /opt/code
    git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
    cd siemens_to_ismrmrd
    mkdir build
    cd build
    cmake ../
    make -j
    sudo make install 
  displayName: "Build Siemens to ISMRMRD"

- script: |
    mkdir build
    cmake ..
    make -j
    sudo make install
  displayName: 'Build Gadgetron'
